name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run forge fmt
        run: forge fmt --check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      # - name: Run deployment script
      #   run: forge script script/deploy-launch.sol

      - name: Run tests
        run: forge test --gas-report

      - name: Run Coverage
        run: forge coverage --report lcov
