name: Slither Analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run Slither
        uses: crytic/slither-action@main
        continue-on-error: true
        id: slither
        with:
          target: "src"
          slither-config: "slither.config.json"
          solc-version: 0.8.17
          sarif: results.sarif

      # - name: Upload SARIF file for core
      #   uses: github/codeql-action/upload-sarif@v2
      #   id: upload-1
      #   with:
      #     sarif_file: ${{ steps.slither.outputs.sarif }}
